language: node_js
node_js:
- '6.9.5'
branches:
  only:
  - master
before_install:
  - rvm install 2.4.1
  - gem install sass
before_script:
- npm install -g grunt-cli
- npm install -g bower
- grunt gh-pages-clean
- bower update
env:
  global:
  - DOCBASE_TOKEN="YjExZDU1Njg0NzQ4Y2M4YWYyNDE2ZTVjMjI1YjQ4ZGY4MzQ0MDgwYg=="
sudo: false
